# version: '3.9'

# services:
#   web:
#     build: .
#     ports:
#       - "8000:8000"
#     volumes:
#       - .:/app
#     environment:
#       - DEBUG=True



version: "3.9"

services:
  web:
    build:
      context: .
      dockerfile: docker/local/Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - docker/local/env.local
    depends_on:
      - db

  db:
    image: postgres:14
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - docker/local/env.local

volumes:
  postgres_data:
