# Generated by Django 5.1.4 on 2024-12-06 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("diary", "0002_rename_resturant_restaurant"),
    ]

    operations = [
        migrations.RenameField(
            model_name="restaurant",
            old_name="cuisuine_type",
            new_name="cuisine_type",
        ),
    ]
