# Generated by Django 5.1.4 on 2024-12-06 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("diary", "0003_rename_cuisuine_type_restaurant_cuisine_type"),
    ]

    operations = [
        migrations.RenameField(
            model_name="visit",
            old_name="resturant",
            new_name="restaurant",
        ),
    ]
