# Generated by Django 5.1.4 on 2024-12-07 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("diary", "0005_cuisinephoto"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cuisinephoto",
            name="description",
        ),
        migrations.AlterField(
            model_name="cuisinephoto",
            name="photo",
            field=models.ImageField(blank=True, null=True, upload_to=""),
        ),
    ]
